// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    [Migration("20210122183433_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ParkAddress");

                    b.Property<string>("ParkName");

                    b.Property<bool>("ParkPetsAllowed");

                    b.Property<bool>("ParkStore");

                    b.Property<string>("ParkType");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkAddress = "55210 238th Avenue East Ashford, WA 98304",
                            ParkName = "Mount Rainier",
                            ParkPetsAllowed = false,
                            ParkStore = true,
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            ParkAddress = "3002 Mount Angeles Road Port Angeles , WA 98362",
                            ParkName = "Olympic",
                            ParkPetsAllowed = true,
                            ParkStore = true,
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            ParkAddress = "810 State Route 20 Sedro-Woolley, WA 98284",
                            ParkName = "North Cascades",
                            ParkPetsAllowed = true,
                            ParkStore = true,
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            ParkAddress = "21588 State Route 207 Leavenworth, WA 98826",
                            ParkName = "Lake Wenatchee",
                            ParkPetsAllowed = true,
                            ParkStore = true,
                            ParkType = "State"
                        },
                        new
                        {
                            ParkId = 5,
                            ParkAddress = "2000 N.W. Sammamish Road Issaqua, WA 98027",
                            ParkName = "Lake Sammamish",
                            ParkPetsAllowed = false,
                            ParkStore = false,
                            ParkType = "State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
